#!/bin/bash

# bash_prompt

# Example:
# nicolas@host: ~/.dotfiles on master [+!?$]
# $

# Screenshot: http://i.imgur.com/DSJ1G.png
# iTerm2 prefs: import Solarized theme (disable bright colors for bold text)
# Color ref: http://vim.wikia.com/wiki/Xterm256_color_names_for_console_Vim
# More tips: http://www.cyberciti.biz/tips/howto-linux-unix-bash-shell-setup-prompt.html


[ -e ~/bin/git-prompt.sh ] && source ~/bin/git-prompt.sh

set_prompts() {
    local black=""
    local blue=""
    local bold=""
    local cyan=""
    local green=""
    local orange=""
    local purple=""
    local red=""
    local reset=""
    local white=""
    local yellow=""

    local hostStyle=""
    local userStyle=""

    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
        tput sgr0 # reset colors

        bold=$(tput bold)
        reset=$(tput sgr0)

        # Solarized colors
        # (https://github.com/altercation/solarized/tree/master/iterm2-colors-solarized#the-values)
        black=$(tput setaf 0)
        blue=$(tput setaf 33)
        cyan=$(tput setaf 37)
        green=$(tput setaf 64)
        orange=$(tput setaf 166)
        purple=$(tput setaf 125)
        red=$(tput setaf 124)
        white=$(tput setaf 15)
        yellow=$(tput setaf 136)
        khaki=$(tput setaf 101)
    else
        bold=""
        reset="\e[0m"

        black="\e[1;30m"
        blue="\e[1;34m"
        cyan="\e[1;36m"
        green="\e[1;32m"
        orange="\e[1;33m"
        purple="\e[1;35m"
        red="\e[1;31m"
        white="\e[1;37m"
        yellow="\e[1;33m"
    fi

    # build the prompt

    # logged in as root
    if [[ "$USER" == "root" ]]; then
        userStyle="$bold$red"
    else
        userStyle="$orange"
    fi

    # connected via ssh
    if [[ "$SSH_TTY" ]]; then
        hostStyle="$khaki"
    else
        hostStyle="$yellow"
    fi

    
    export GIT_PS1_SHOWDIRTYSTATE=1        # unstaged (*) and staged (+)
    export GIT_PS1_SHOWSTASHSTATE=1        # stashed ($)
    export GIT_PS1_SHOWUNTRACKEDFILES=1    # untracked (%)
    export GIT_PS1_SHOWUPSTREAM="auto"     # behind (<), ahead (>), diverged (<>), no diff (=)
    export GIT_PS1_SHOWCOLORHINTS=1        # colored output


#    PS_pre+="\n" # newline
    PS_pre="\[\033]0;\w\007\]" # set the terminal title to the current working directory
    PS_pre+="\[$userStyle\]\u" # username
    PS_pre+="\[$reset$yellow\]@"
    PS_pre+="\[$hostStyle\]\h" # host
    PS_pre+="\[$reset$yellow\]: "
    PS_pre+="\[$green\]\w" # working directory
    PS_pre+="\[$reset\]"
    PS_post="\n"
    PS_post+="\[$reset$white\]\$ \[$reset\]" # $ (and reset color)
    PROMPT_COMMAND='__git_ps1 "$PS_pre" "$PS_post"'

}

set_prompts
unset set_prompts

